# ansible-playbook -K shield_deploy.yaml   

- name: Shield Deployment Ansible Playbook
  hosts: vbox

# make a variable for /home/herraiz/shield

  vars:
    SHIELD_DIR: /home/herraiz/shield

  tasks:

# Environment var creation

    - name: Clone shield project from github
      git:
        clone: yes
        repo: https://github.com/RoberHerraiz/shield.git
        dest: '{{ SHIELD_DIR }}'

    # - name: Replace /etc/ssh/sshd_config (replace)
    #   replace:
    #     path: /etc/ssh/sshd_config
    #     regexp: ^PasswordAuthentication no$
    #     replace: PasswordAuthentication yes