- name: Shield Deployment Ansible Playbook
  hosts: all

  vars:
    SHIELD_DIR: /var/www/shield

  tasks:

# sudo management

    - name: installing sudo
      become: yes
      apt:
        name: sudo
        update_cache: yes


# Packages installation

    - name: Installing packages with apt
      become: yes
      apt:
        name: git, nginx, python3-pip, python3-venv
        update_cache: yes


# Clone project from GitHub

    - name: Cloning shield project from GitHub
      become: yes
      git:
        clone: yes
        repo: https://github.com/RoberHerraiz/shield.git
        dest: '{{ SHIELD_DIR }}'
        force: yes

# Virtual Env creation

    - name: Creating VirtualEnv
      become: yes
      command: python3 -m venv '{{ SHIELD_DIR }}/venv'


# Dependencies installation

    - name: Installing wheel
      become: yes
      pip:
        name: wheel
        virtualenv: '{{ SHIELD_DIR }}/venv'

    - name: Installing pip requirements
      become: yes
      pip:
        requirements: '{{ SHIELD_DIR }}/requirements.txt'
        virtualenv: '{{ SHIELD_DIR }}/venv'


# Migrations and data load

    - name: Making migrations - Django
      django_manage:
        command: makemigrations
        app_path: '{{ SHIELD_DIR }}'
        virtualenv: '{{ SHIELD_DIR }}/venv'

    - name: Migrate - Django
      django_manage:
        command: migrate
        app_path: '{{ SHIELD_DIR }}'
        virtualenv: '{{ SHIELD_DIR }}/venv'

    - name: Loading data - Django
      become: yes
      django_manage:
        command: loaddata
        fixtures: '{{ SHIELD_DIR }}/metahumans/dumpdata.json' 
        app_path: '{{ SHIELD_DIR }}'
        virtualenv: '{{ SHIELD_DIR }}/venv'


# Static optimization

# Static_root modified at repo

    - name: Collecting static - Django
      become: yes
      django_manage:
        command: collectstatic
        app_path: '{{ SHIELD_DIR }}'
        virtualenv: '{{ SHIELD_DIR }}/venv'
      

# Adjust permissions

    - name: Changing file permissions for www-data
      become: yes
      file:
        path: '{{ SHIELD_DIR }}'
        state: directory
        recurse: yes
        group: www-data
        owner: www-data


# uWSGI config

    - name: Installing uWSGI
      become: yes
      pip:
        name: uwsgi
    
    - name: Creating vassals directory
      become: yes
      file:
        path: /etc/uwsgi/vassals
        state: directory


# Vassal config

# 'uwsgi.ini' file was uploaded to github shield's project

    - name: Creating vassal directory
      become: yes
      file:
        path: '/var/log/uwsgi/'
        state: directory
        recurse: yes

    - name: Creating logto file and changing permissions
      become: yes
      file:
        path: '/var/log/uwsgi/shield.log'
        state: touch
        owner: www-data

    - name: Creating symlink for uwsgi.ini
      become: yes
      file:
        src: '{{ SHIELD_DIR }}/uwsgi.ini'
        path: '/etc/uwsgi/vassals/shield.ini'
        state: link

# Emperor configuration

#'emperor.ini' and 'uwsgi-emperor.service' files were uploaded to github shield's project

    - name: Moving emperor.ini to /etc/uwsgi
      become: yes
      copy:
        remote_src: yes
        src: '{{ SHIELD_DIR }}/emperor.ini'
        dest: '/etc/uwsgi/'

    - name: Moving emperor service to /etc/systemd/system/
      become: yes
      copy:
        remote_src: yes
        src: '{{ SHIELD_DIR }}/uwsgi-emperor.service'
        dest: '/etc/systemd/system/'     

    - name: Reloading daemons
      become: yes
      systemd:
        daemon_reload: yes

    - name: Starting and enabling start-on-boot of uwsgi-emperor service
      become: yes
      service:
        name: uwsgi-emperor
        state: started
        enabled: yes


# Nginx configuration

    - name: Deactivating default nginx welcome page
      become: yes
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent # delete

    - name: Moving nginx config file from repo
      become: yes
      copy:
        remote_src: yes
        src: '{{ SHIELD_DIR }}/shield.conf'
        dest: '/etc/nginx/sites-available/'

    - name: Creating symlink to sites-enabled
      become: yes
      file:
        src: '/etc/nginx/sites-available/shield.conf'
        path: '/etc/nginx/sites-enabled/shield.conf'
        state: link
    
    - name: Restart nginx
      become: yes
      service:
        name: nginx
        state: restarted
        enabled: yes